### ISSUE TITLE
Tweaking the UI

### ISSUE THREAD

**Issue by mohkale** [flexibeast/ebuku#1]
love the plugin, but I feel the UI could use some work. 

Seeing as ebuku is a command line application, having a magit like interface would be nicer. Meaning we should have transient or hydra as a dependency. I'm personally more familliar with hydra so I say we should go with that, but transient seems like a better fit.

We should also introduce some nicer defaults for the faces used. Right now most just inherit from `default` which gives the ebuku buffer a somewhat dull look of pure white (not that there's anything wrong with that).

URLs at the moment are just plaintext. We should make them both clickable and actionable. Hovering over a URL and clicking it (or pressing enter) should open the URL like it would in org mode.

We should also introduce methods for moving to the next or previous search result. Furthermore we should have functions to jump to search results in the current buffer by title or url like `counsel-org-goto`.

S.N. `ebuku-buku-path` is hardcoded as a unix like path. Which means users on windows will have to change it before they can use the plugin. We should change the definition to `"buku"` if you're on windows & keep it as `"/bin/duku"` if your on any other OS.

**Comment by flexibeast** [comment]
Thank you for the constructive feedback!

> Seeing as ebuku is a command line application

Sorry, did you mean to write that *Buku* is a command line application?

> having a magit like interface would be nicer. Meaning we should have transient or hydra as a dependency. I'm personally more familliar with hydra so I say we should go with that, but transient seems like a better fit.

i'm very open to implementing this, but i only use transient via magit, and don't use hydra at all, so i'm not sure of the pros and cons of using one compared to the other. Could you elaborate on why you feel transient seems like a better fit? (And do you know if it's possible to support both, and let the user choose which one to use?)

> We should also introduce some nicer defaults for the faces used. Right now most just inherit from default

Yes, this is intentional, based on what i believe to be best practice, as described in [MELPA's CONTRIBUTING document](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org):

> Please avoid defining a face that both :inherit another face and also override their attributes (e.g. by making them bold, underlined or inverse-video). The result could be really bad depending on user customizations. The best approach here is to simply :inherit the faces, and leave the user to customise the rest.

If you have any suggestions as to better faces to inherit from, please let me know!

> URLs at the moment are just plaintext. We should make them both clickable and actionable.

Good idea: created as issue #2.

> We should also introduce methods for moving to the next or previous search result. 

Sure: created as issue #3.

> Furthermore we should have functions to jump to search results in the current buffer by title or url like counsel-org-goto.

i'm not sure i understand what you mean here; could you please describe this in more detail?

> We should change the definition to "buku" if you're on windows & keep it as "/bin/duku" if your on any other OS.

Sure: created as issue #4.

**Comment by mohkale** [comment]
> Sorry, did you mean to write that Buku is a command line application?

Yep. I only encountered it through your plugin yesterday, and truth be told... I'm having an *extremely* hard time remembering it's name. I've aliased it to simply `b` in my shell, but you'll have to excuse any mispellings going forward. Sorry in advance 😞.

> Could you elaborate on why you feel transient seems like a better fit? 

[Transient](https://github.com/magit/transient) was designed to make interfaces for command like applications in emacs. Initially for magit. Now I'd argue the goto package for doing so would be transient, simply looking at the screenshot ![transient](https://camo.githubusercontent.com/24772090c2686322ee40642d8ff64a39d248e265/687474703a2f2f726561646d652e656d6163736169722e6d652f7472616e7369656e742e706e67) you can see the program flags and options, (& even cooler, **active** options) alongside a list of the commands you can run.

I'm not at all familliar with how to create transient bindings, so I'd have to look it up; but I'm more than willing to go that route if that's what we decide.

As for [Hydras](https://github.com/abo-abo/hydra), their designed for simply grouping commands together and giving them top level control while the hydra is active. Their extremely simple to make & I'd highly recommand introducing a few into your emacs life. 

I suggest looking at the github pages of both to see the larger differences. We could go with either, but I don't think going with both will be that easy. At the very least, I haven't seen any package that uses hydra or transient offer both seperately.

> Yes, this is intentional, based on what i believe to be best practice, as described in MELPA's CONTRIBUTING document:

Makes sense, though I'd still prefer them inheriting from different faces (than just the default one). We'll have to look into that, but it's not a high priority.

I do suggest whichever faces we choose, the final interface should look like the output of running buku on the command line.

> i'm not sure i understand what you mean here; could you please describe this in more detail?

Hard to describe off the cuff, I'll just post some screenshots of me in an org buffer to summarise.

![Capture](https://user-images.githubusercontent.com/23294780/70951808-55fdd500-205c-11ea-8b45-d22818fecef6.PNG)

Here I am in an org buffer. I've run `counsel-org-goto` and I'm presented with a list of all the 
org headings in my buffer. I can enter a regular expression to help match some heading I want to go to & if I then hit return my `(point)` is moved to that header position.

**Comment by mohkale** [comment]
I see you've basically got the last point down in issue #5, that's basically what I meant.

**Comment by flexibeast** [comment]
> the final interface should look like the output of running buku on the command line.

i've decided that i'm not going to change which colours are used by default, for two reasons:

* the default colour scheme for buku is not helpful for people who are red-green colourblind (who, [according to Wikipedia](https://en.wikipedia.org/wiki/Color_blindness), represent "up to 8% of males and 0.5% of females of Northern European descent").

* more generally, i really don't want to get into bikeshedding over the default colour scheme. i feel that as long as people can change the colours to a set that works best for them, that's sufficient.

**Comment by flexibeast** [comment]
Re. `transient` / `hydra`  - i'm very familiar with `transient` via my regular use of `magit`, but i'm not convinced that using `transient` would provide a significant enough benefit to be worth making it a dependency. Could you please describe what you think the benefits would be? Is it that one could (say) press <kbd>h</kbd> to get a `transient` window showing the available commands, rather than having to use <kbd>C-h m</kbd>?

**Comment by mohkale** [comment]
Honestly I don't think I've really used buku very much, meaning I haven't used this plugin all that much either. So I can't think of any real benefits to tweaking the UI at this point. I'll close this issue, thnx for taking the time to hear me out :smile:.
