### ISSUE TITLE
Error:   No results found for '--print -1000'.

### ISSUE THREAD

**Issue by E3D3** [flexibeast/ebuku#14]
I installed ebuku with ELPA "M-x package-list-packages" on GNU Emacs 25.1.50.1 (x86_64-pc-linux-gnu, GTK+ Version 3.14.5) of 2016-10-29, modified by Debian (and using emacs-distribution).
After opening the ebuku buffer (Mx- ebuku) it shows/rapports only:

   **Ebuku**

   No results found for '--print -1000'.

The number change when I change "ebuku-results-limit".
Any idea what is wrong ?

**Comment by flexibeast** [comment]
Just to confirm: your buku database does actually contain entries? That is, do you get results if you run "buku --print -1000" on the command line?

**Comment by E3D3** [comment]
Yes, buku works very nice in the terminal, and "buku --print -1000" prints the last 1000 database entries.

**Comment by flexibeast** [comment]
Okay, so what happens if you ask Ebuku to show the most recently-added bookmarks, by pressing `r`?

**Comment by E3D3** [comment]
Found 3 results for '--print -3'.

**Comment by E3D3** [comment]
I just remember that this Emacs (via emacs-distribution) assign ~ to its own folder. Guess that could be the problem, when searching for the buku-database.

**Comment by flexibeast** [comment]
Hmm, but if Ebuku couldn't find the buku database, then i would expecteit to not list any results when doing a 'recent' search .... Do you still get no results when pressing `*` in the same instance of Emacs in which you pressed `r`?

**Comment by E3D3** [comment]
Yes that's it. I'm so sorry to bothered you with this.
Making a symlink to the buku db-file in the emacs-distribution directory solved the problem; ebuku shows my bookmarks.

**Comment by E3D3** [comment]
although I have to execute "M-x ebuku" twice before the bookmarks show up. Every first time I get the error: Args out of range: "IC PDF Search", 5, 43. But the 2nd time it looks good.

**Comment by E3D3** [comment]
btw, I didn't get results before when pressing '*', 'r', 's' or whatever

**Comment by E3D3** [comment]
and now that I see the bookmarks, I can't  get mode-help (C-h m) wich explains the keybindings, but this is due to a corrupt db-file (forbidden characters in URL's). Cleaning the URL's solved this. To bad I can't clean the URL's with ebuku.

**Comment by E3D3** [comment]
can this be due to corrupt database. I just imported 5000 old bookmarks in buku and didn't clean all URL's from forbidden characters (&, ; { etc) yet ?

**Comment by flexibeast** [comment]
Well, if buku itself is able to print out the bookmark fine, but Ebuku has problems with it, then that's a bug in Ebuku. :-) If that's the case, could you please provide several examples of where Ebuku is failing, so that i can improve the code?

**Comment by E3D3** [comment]
Sorry again to bother you with something I could solve myself, although I could be your good vibes that gave me suddenly the right thought. Thanks for your time, making and sharing ebuku, that seems to works like expected now.

**Comment by E3D3** [comment]
ebuku only failed when I loaded it with a database where many URL's still have forbidden characters, mostly bookmarklets that have javascript as URL's. I need to ask buku's developper if I can quote such lines correctly. I guess that you can repeat the problem by corrupting some URL's with ';' '&' etc.

**Comment by flexibeast** [comment]
> Sorry again to bother you with something I could solve myself, although I could be your 
good vibes that gave me suddenly the right thought.

That's okay - sometimes talking through the problem with someone else can be the best way to solve it, and anyway, it's good for me to know about this situation, so i can maybe help others in the future.

> Thanks for your time, making and sharing ebuku, that seems to works like expected now.

You're welcome - thank you for your positive feedback!

i'll close this particular issue.

> a database where many URL's still have forbidden characters, mostly bookmarklets that have javascript as URL's. I need to ask buku's developper if I can quote such lines correctly.

Ah, bookmarklets, i'd forgotten about them .... Well, if you can get them working with buku, please do feel free to open an issue here about making sure that Ebuku supports them also.
