### ISSUE TITLE
Evil bindings

### ISSUE THREAD

**Issue by dppdppd** [flexibeast/ebuku#21]
Thanks for the mode!

I’m running doom and have “evil +everything,” which should include evil-collection. 

However nothing is bound to any of the ebuku commands. 

What am I missing?

**Comment by flexibeast** [comment]
You're welcome. :-)

i'm actually only an occasional user of Evil myself (via `evil-local-mode`), and certainly don't use the bindings i added to `evil-collection` for Evil users; do other bindings in `evil-collection` work?

**Comment by dppdppd** [comment]
Solved. It needs to be manually added to the collection list. TIL.

>(after! ebuku
  :init
  (pushnew! evil-collection-mode-list 'ebuku)
  (evil-collection-init))
