### ISSUE TITLE
compile warnings for version 20220521.1416

### ISSUE THREAD

**Issue by E3D3** [flexibeast/ebuku#25]
I have Emacs 27.1 and ebuku version 20220521.1416, and got the following compiler warnings when updating ebuku:

```
In ebuku--search-helper:
ebuku.el:613:20:Warning: ‘goto-line’ is for interactive use only; use
    ‘forward-line’ instead.
ebuku.el:651:37:Warning: ‘goto-line’ is for interactive use only; use
    ‘forward-line’ instead.

In ebuku-refresh:
ebuku.el:907:66:Warning: ‘goto-line’ is for interactive use only; use
    ‘forward-line’ instead.
ebuku.el:909:12:Warning: ‘goto-line’ is for interactive use only; use
    ‘forward-line’ instead.

In ebuku:
ebuku.el:1026:12:Warning: ‘goto-line’ is for interactive use only; use
    ‘forward-line’ instead.

In end of data:
ebuku.el:1043:1:Warning: the following functions are not known to be defined:
    string-empty-p, map-put, text-property-search-backward,
    text-property-search-forward, map-elt, seq-uniq
```
I didn't notice any negative effect of this, yet, only want to inform you about it, and ofcourse want to thank you for making & sharing Ebuku.

**Comment by flexibeast** [comment]
Thanks for the report! i've just pushed some changes that should eliminate the warnings about `goto-line`; let me know.

The "following functions are not known to be defined" warnings are odd. The only warnings i now get when byte-compiling the file are about `map-put` being obsolete (which i'm aware of, and will not address until 27.1-and-newer have been around for longer). From the docstrings in 28.1:

* `string-empty-p`: "Probably introduced at or before Emacs version 24.4."
* `map-put`: "Probably introduced at or before Emacs version 26.1."
* `text-property-search-backward`: "Probably introduced at or before Emacs version 27.1."
* `text-property-search-forward`: "Probably introduced at or before Emacs version 27.1."
* `map-elt`: "Probably introduced at or before Emacs version 26.1."
* `seq-uniq`: No introduction date provided, but `seq.el` overall dates back to 2014.

i'll leave this issue open in case you or anyone else can shed further light on these warnings.

**Comment by E3D3** [comment]
After updating `ebuku` today again, I've got only one warning

> In end of data:
ebuku.el:1051:1:Warning: the following functions are not known to be defined:
    string-empty-p, map-put, text-property-search-backward,
    text-property-search-forward, map-elt, seq-uniq

I'm too bad in elisp to tell more than that I have these undefined functions, and `ebuku' still works without problems.

**Comment by flexibeast** [comment]
Well, they certainly get defined at some point, since otherwise `ebuku` wouldn't work. :-) But yeah, as my previous comment noted, they're all functions that should be provided by Emacs 27.1. Do you also get this warning when running `emacs -Q -l /path/to/ebuku.el`? If not, there would seem to be something unique to your local configuration causing this issue.

**Comment by E3D3** [comment]
`emacs -Q -l /path/to/ebuku.el` doesn't give me any warnings.
I also tested it by installing `ebuku` in another emacs distro ([NΛNO](https://github.com/rougier/nano-emacs)] and got again zero warnings.
So I believe you that the warning has to do with my personal configuration.
Sorry to have bothered you with this, and thank you for the ~~fish~~ help.

**Comment by flexibeast** [comment]
Sorry, didn't realise i hadn't acknowledged or responded to your last comment! Hope you've since resolved the issue. Closing.
