### ISSUE TITLE
No items are listed

### ISSUE THREAD

**Issue by rakanalh** [flexibeast/ebuku#6]
Hello

I have installed buku and ebuku and set `ebuku-buku-path` to `/usr/bin/buku` which is where the executable is.

However, ebuku does not list any items

![DeepinScreenshot_select-area_20191219144751](https://user-images.githubusercontent.com/195829/71178573-c67c4000-226e-11ea-8777-8d8cee57a17c.png)
![DeepinScreenshot_select-area_20191219144801](https://user-images.githubusercontent.com/195829/71178580-c9773080-226e-11ea-8949-f758b05ccea9.png)

I don't see any errors being displayed so i think this is a bug somewhere.

**Comment by flexibeast** [comment]
No bug; it's working as designed. i have 40,000+ bookmarks in my database, accumulated over the course of decades, so i deliberately chose to not display all the database contents when EBuku starts.

That said, this behaviour was clearly unexpected to you, so i obviously need to do something about it. :-) i propose the following:

* Have an option where the user specifies whether to display all bookmarks on EBuku startup, only the most recently-added[1], or none at all. i'd probably make the first option the default, but add in some code to warn the user if more than (say) 1000 bookmarks would be displayed.

[1] The ability to display the most-recently added bookmarks is available in the `recently-added` branch. i'm not going to merge this, or other improvements, into `master` until the package has passed muster with the MELPA reviewers (cf. https://github.com/melpa/melpa/pull/6545), to ensure they have a stable codebase to review.

* When the previous option is set to `nil`, on startup EBuku will display a message along the lines of "Please specify a search".

How does all that sound?

**Comment by rakanalh** [comment]
Sounds great. I guess it makes alot of sense to list the recently added ones.

However, for me even when pressing `s` and `l` for all i get:
```
 No results found for '--sall '.
```

that is, without specifying keywords or excluded keywords. When i press `s a` for any, i get nothing.

**Comment by flexibeast** [comment]
Hmm, i think part of the issue here might be that (it seems) you're not familiar with Buku. Are you new to it? You *need* to specify search terms: Buku's `--sall` option doesn't mean "Show all results", it means "Search for *all* the terms specified": 

> -S --sall keyword [...]
>     Search bookmarks with ALL keywords in URL, title or tags and
>     show the results. Behaviour same as --sany.
>     Special keywords:
>     "blank": list entries with empty title/tag
>     "immutable": list entries with locked title
>     NOTE: To search the keywords, use --sany

Similarly, `--sany` doesn't mean "Show any results"; here's the first part of the documentation for `--sany`:

> -s --sany keyword [...]
              Search bookmarks with ANY of the keyword(s) in URL, title or
              tags and show the results.

EBuku is designed around the functionality and behaviour of the Buku UI, and assumes the user is familiar with Buku itself.

**Comment by flexibeast** [comment]
Addressed in https://github.com/flexibeast/ebuku/commit/5e8063f59d6197a5d540aa2d026a70cce9a8d558; closing.
