### ISSUE TITLE
Evil support

### ISSUE THREAD

**Issue by rakanalh** [flexibeast/ebuku#8]
Alot of emacs users use evil for their keybindings. I noticed that in ebuku-mode, provided that the evil layer is activated, i would have to go into insert-mode before being able to press `a` to add a new bookmark, or `d` to delete.

Would be great if this package can also provide direct keybindings or mention a way to make this work nicely with evil.

**Comment by flexibeast** [comment]
Yes, i would like to support Evil users (although i only use `evil-local-mode` myself). How do Evil users work with Emacs 'apps' like Dired, which already has single-key bindings? Would the implementation of support for transient or hydra, as per #1, address this issue?

**Comment by rakanalh** [comment]
To be honest, i don't think i can answer your question about how evil works with dired... but i guess the keys that ebuku introduces have to be bound to normal state somehow. I don't think hydra is the solution here.

**Comment by flexibeast** [comment]
Hmm, okay. Well, i might have to ask for help on r/emacs about this, to find out what the best practices are in this sort of situation.

**Comment by yyoncho** [comment]
@rakanalh consider `M-x` `evil-evilified-state`

**Comment by noctuid** [comment]
I think it would make more sense to just bind the keys yourself (or do some other personal configuration) or to create a file in evil-collection rather than do anything in this package.

**Comment by flexibeast** [comment]
Bindings for Evil are now available via the `evil-collection` package - cf. https://github.com/emacs-evil/evil-collection/pull/301. Closing.
